[package]
name = "todo-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
r2d2 = "0.8"
r2d2_sqlite = "0.24"
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1", features = ["serde_derive"] }
